-- Ebun local development seed data.
-- Intentionally empty — the launch catalog moved to a real migration
-- (supabase/migrations/20260927000000_seed_launch_gift_catalog.sql)
-- since it's real product data meant for every environment, not
-- throwaway local fixtures. This file is for genuinely dev-only,
-- disposable data, if that's ever needed later.
