import { Inject, Injectable } from '@nestjs/common';
import type { PostgrestError, SupabaseClient } from '@supabase/supabase-js';
import { OrderStatus } from '@ebun/types';
import { SUPABASE_CLIENT } from '../supabase/supabase.module';

/** Mirrors the schema's actor_type enum — kept local since only this
 * repository's RPC call needs it; not worth a shared package export
 * for one parameter type. */
export type OrderTransitionActorType =
  'user' | 'vendor' | 'system' | 'webhook' | 'admin' | 'cron';

export interface AttemptOrderTransitionParams {
  orderId: string;
  expectedStatus: OrderStatus;
  newStatus: OrderStatus;
  actorType: OrderTransitionActorType;
  actorId?: string | null;
  metadata?: Record<string, unknown> | null;
}
export interface OrderRow {
  id: string;
  status: OrderStatus;
  order_number: string | null; // EBN-XXXX — generated by a DB trigger, never set by us
  total_amount: number; // kobo — explicit because callers (e.g. PaystackWebhookService) compare/interpolate it directly, not just pass it through
  [key: string]: unknown;
}

export interface CreateOrderParams {
  senderId: string;
  giftTemplateId: string;
  recipientName: string;
  recipientPhone: string;
  senderMessage?: string | null;
  messageType?: string | null;
  scheduledSendAt?: string | null;
  paystackReference: string;
  totalAmount: number;
  giftValue: number;
  deliveryFee: number;
  serviceFee: number;
  senderIp?: string | null;
  senderCountryCode?: string | null;
  isDiasporaSender: boolean;
}
/**
 * Thin wrapper around attempt_order_transition() (see
 * supabase/migrations — attempt_order_transition.sql). Deliberately does
 * NOT validate whether the transition is legal — that's
 * OrderStateMachineService's job and must happen before this is called.
 * This class only owns the atomic write itself.
 */
@Injectable()
export class OrdersRepository {
  constructor(
    @Inject(SUPABASE_CLIENT) private readonly supabase: SupabaseClient,
  ) {}

  /**
   * Returns the updated order row on success, or null if the compare-
   * and-swap failed — the order doesn't exist, or its status no longer
   * matches expectedStatus (a concurrent writer won the race). Null is
   * a normal, expected outcome to handle, not necessarily a bug.
   */
  async attemptTransition(
    params: AttemptOrderTransitionParams,
  ): Promise<OrderRow | null> {
    // Cast the response itself, not just the destructuring target —
    // without a generated Supabase `Database` type wired into
    // createClient() (no `supabase gen types typescript` step in the
    // build yet), .rpc()'s return type resolves to `any` all the way
    // through, and annotating only the destructured variables doesn't
    // change the assignment SOURCE's inferred type, so
    // @typescript-eslint/no-unsafe-assignment still fires. Casting the
    // awaited expression fixes that at the source. Once generated types
    // exist, this can simplify to createClient<Database>(...) at the
    // SupabaseModule level instead of casting at every call site.
    const response = (await this.supabase.rpc('attempt_order_transition', {
      p_order_id: params.orderId,
      p_expected_status: params.expectedStatus,
      p_new_status: params.newStatus,
      p_actor_type: params.actorType,
      p_actor_id: params.actorId ?? null,
      p_metadata: params.metadata ?? null,
    })) as { data: OrderRow | null; error: PostgrestError | null };

    if (response.error) {
      // Let this surface as-is for now — a global exception filter can
      // translate Postgres/PostgREST errors into HTTP responses once
      // one exists. Swallowing it here would hide real failures
      // (connection errors, bad enum values, etc.) behind a plain null.
      throw response.error;
    }

    return response.data ?? null;
  }

  /**
   * Reads an order by its Paystack transaction reference. Returns null if none exists — a normal, expected outcome for the caller to check (e.g. a webhook referencing an order that was never created by us), not necessarily a bug.
   */
  async findByPaystackReference(reference: string): Promise<OrderRow | null> {
    const response = (await this.supabase
      .from('orders')
      .select('id, status, total_amount, paystack_reference')
      .eq('paystack_reference', reference)
      // .maybeSingle(), not .single() — returns null for zero matches instead of erroring; still errors if more than one row matches, which would indicate a real data-integrity problem (paystack_reference is UNIQUE in the schema, so that should be impossible, but this doesn't silently paper over it if it ever isn't).
      .maybeSingle()) as {
      data: OrderRow | null;
      error: PostgrestError | null;
    };

    if (response.error) {
      throw response.error;
    }

    return response.data ?? null;
  }

  /**
   * The one place a new order row is ever inserted. Always as 'draft' —
   * matches both the schema's column default and the state machine's
   * only entry point (see order-state-machine.ts: nothing transitions
   * INTO draft, only out of it). order_number is deliberately absent
   * from the insert payload — a DB trigger (trg_order_number) generates
   * it automatically; setting it ourselves would just be overwritten
   * unless it were non-null/non-empty, in which case we'd risk a
   * collision with the trigger's own sequence.
   */
  async create(params: CreateOrderParams): Promise<OrderRow> {
    const response = (await this.supabase
      .from('orders')
      .insert({
        status: 'draft',
        sender_id: params.senderId,
        gift_template_id: params.giftTemplateId,
        recipient_name: params.recipientName,
        recipient_phone: params.recipientPhone,
        sender_message: params.senderMessage ?? null,
        message_type: params.messageType ?? null,
        scheduled_send_at: params.scheduledSendAt ?? null,
        paystack_reference: params.paystackReference,
        total_amount: params.totalAmount,
        gift_value: params.giftValue,
        delivery_fee: params.deliveryFee,
        service_fee: params.serviceFee,
        sender_ip: params.senderIp ?? null,
        sender_country_code: params.senderCountryCode ?? null,
        is_diaspora_sender: params.isDiasporaSender,
      })
      .select()
      .single()) as { data: OrderRow | null; error: PostgrestError | null };

    if (response.error) {
      throw response.error;
    }
    if (!response.data) {
      throw new Error('Order insert returned no data');
    }

    return response.data;
  }
}
