import { OrderStatus } from '@ebun/types';

/**
 * =============================================================================
 * ORDER STATE MACHINE
 * =============================================================================
 *
 * The single authority for "is this order status change allowed?". Every
 * module that ever writes `orders.status` (payments on webhook confirm,
 * fulfillment on vendor accept/decline, redemption on claim, cron jobs for
 * timeout/expiry, a future ops/admin module) must validate through this file
 * — via OrderStateMachineService — before writing to the database. The
 * schema's own migration comment says it plainly: "state transitions are
 * enforced in NestJS, not [in Postgres]." Do not reimplement this check
 * inline anywhere else.
 *
 * EVIDENCE PROVENANCE
 * --------------------
 * Every edge below is tagged with where it came from. These are NOT
 * interchangeable — they carry different confidence levels and different
 * review requirements:
 *
 *   SCHEMA    Taken verbatim from the `order_status` enum's transition
 *             comment block in the applied migration
 *             (supabase/migrations/20260817040312_ebun_initial_schema.sql).
 *             Highest confidence — this is what the schema's author wrote
 *             down as the intended lifecycle.
 *
 *   DERIVED   Not stated in that comment, but forced by *executable* code
 *             elsewhere in the same migration — a function body or an index
 *             predicate. Treated as equally authoritative to SCHEMA because
 *             it's backed by code that actually runs, not prose. Every
 *             DERIVED edge below cites exactly which function/index forced
 *             it.
 *
 *   INFERRED  The enum defines the state, but nothing in the schema wires it
 *             into the graph anywhere — no comment, no function, no index.
 *             Filled in from the Product Brief's failure-scenario language,
 *             using the most conservative interpretation available.
 *             NEEDS PRODUCT/OPS CONFIRMATION before this ships to
 *             production — flagged individually below and in the test file.
 *
 * NORMAL vs ADMIN OVERRIDE
 * -------------------------
 * The graph is split into two separate, independently-checked maps:
 *
 *   NORMAL_TRANSITIONS         Driven by webhooks, vendor actions, recipient
 *                               actions, or cron jobs — the automatic
 *                               pipeline. No human judgment call involved.
 *
 *   ADMIN_OVERRIDE_TRANSITIONS  The Brief's "[any] → refunded (admin action)"
 *                               and "[any] → cancelled" language. Represents
 *                               an ops/admin actor stepping in outside the
 *                               normal flow (audit_events.actor_type =
 *                               'admin', not 'system'/'webhook'/'cron').
 *
 * These are deliberately NOT merged into one combined table. A caller that
 * wants to perform a normal, system-driven transition calls
 * `assertNormalTransition()`, which only ever consults NORMAL_TRANSITIONS.
 * A caller performing an admin override (which should sit behind an RBAC
 * guard requiring ebun_ops/ebun_admin) calls `assertAdminOverrideTransition()`
 * explicitly. If these were merged, a bug in (say) the payments webhook
 * handler could silently walk an order straight to `refunded` just because
 * that edge exists *somewhere* in a combined table — separating them makes
 * that class of bug structurally impossible rather than relying on someone
 * remembering to check.
 */

/**
 * Normal lifecycle transitions. Every one of the 22 OrderStatus members has
 * an explicit entry — deliberately hand-written rather than generated by
 * iterating the enum, so each state's allowed transitions are readable and
 * auditable in place, without tracing through a builder function.
 */
export const NORMAL_TRANSITIONS: Readonly<
  Record<OrderStatus, ReadonlyArray<OrderStatus>>
> = {
  [OrderStatus.Draft]: [
    OrderStatus.PendingPayment, // SCHEMA
  ],

  [OrderStatus.PendingPayment]: [
    OrderStatus.Paid, // SCHEMA
    OrderStatus.PaymentFailed, // SCHEMA
  ],

  [OrderStatus.Paid]: [
    OrderStatus.Processing, // SCHEMA
  ],

  [OrderStatus.Processing]: [
    OrderStatus.VendorNotified, // SCHEMA
    OrderStatus.FulfillmentInProgress, // SCHEMA — VTU/digital bypasses vendor notification entirely
  ],

  [OrderStatus.VendorNotified]: [
    OrderStatus.VendorAccepted, // SCHEMA
    OrderStatus.VendorDeclined, // SCHEMA
    OrderStatus.VendorTimeout, // SCHEMA
  ],

  [OrderStatus.VendorAccepted]: [
    OrderStatus.FulfillmentInProgress, // SCHEMA
    // INFERRED — vendor confirmed, then failed to deliver on that promise.
    // "fulfillment_failed" enum comment says "vendor/VTU/delivery failure,
    // not resolved" but the schema never states which source states reach
    // it. This is the earliest point a *committed* vendor could fail.
    // CONFIRM WITH PRODUCT before relying on this in the fulfillment module.
    OrderStatus.FulfillmentFailed,
  ],

  [OrderStatus.VendorDeclined]: [
    OrderStatus.Processing, // SCHEMA — reassignment to backup vendor
  ],

  [OrderStatus.VendorTimeout]: [
    OrderStatus.Processing, // SCHEMA — reassignment to backup vendor
  ],

  [OrderStatus.FulfillmentInProgress]: [
    OrderStatus.Dispatched, // SCHEMA — physical gifts
    OrderStatus.ReadyForRedemption, // SCHEMA — schema's literal wording for "digital"
    // DERIVED — voucher_issued is the digital_voucher fulfillment_type's
    // specific path (see gift_fulfillments.voucher_issued_at /
    // .voucher_valid_until, which only make sense for this branch), sitting
    // alongside — not instead of — the schema's generic "digital" edge to
    // ready_for_redemption used by vtu/experience fulfillment types.
    OrderStatus.VoucherIssued,
    // INFERRED — delivery/preparation failure while actively fulfilling.
    // CONFIRM WITH PRODUCT.
    OrderStatus.FulfillmentFailed,
  ],

  [OrderStatus.Dispatched]: [
    OrderStatus.Delivered, // SCHEMA
    // INFERRED — rider/delivery failure after dispatch (lost parcel, refused
    // at door, etc). CONFIRM WITH PRODUCT.
    OrderStatus.FulfillmentFailed,
  ],

  [OrderStatus.Delivered]: [
    OrderStatus.RevealOpened, // SCHEMA
    OrderStatus.Fulfilled, // SCHEMA — "if no reveal required"
  ],

  [OrderStatus.VoucherIssued]: [
    // DERIVED — mirrors ready_for_redemption's own edge to reveal_opened.
    // Both are "voucher/QR handed to recipient, awaiting their action"
    // states; idx_orders_expires groups them identically (see below).
    OrderStatus.RevealOpened,
    // DERIVED — expire_unclaimed_gifts() runs:
    //   UPDATE orders SET status = 'expired' ...
    //   WHERE status IN ('ready_for_redemption','reveal_opened','voucher_issued')
    //     AND expires_at < now();
    // voucher_issued is explicitly in that batch, alongside the two states
    // the schema's prose comment does mention — so an unrevealed voucher can
    // expire without ever passing through reveal_opened, exactly like
    // ready_for_redemption can.
    OrderStatus.Expired,
  ],

  [OrderStatus.ReadyForRedemption]: [
    OrderStatus.RevealOpened, // SCHEMA
    // DERIVED — same expire_unclaimed_gifts() batch UPDATE as above;
    // ready_for_redemption is one of the three states in its WHERE clause.
    // The schema's prose comment only shows reveal_opened → expired, but the
    // function proves ready_for_redemption can expire directly too.
    OrderStatus.Expired,
  ],

  [OrderStatus.RevealOpened]: [
    OrderStatus.Redeemed, // SCHEMA
    OrderStatus.Expired, // SCHEMA
    // INFERRED — redemptions.redemption_attempts hits
    // redemptions.max_attempts (schema: "after max, ops must manually
    // unlock"). This models that exhaustion surfacing on the order itself.
    // CONFIRM WITH PRODUCT — it's also plausible this never touches
    // orders.status at all and stays entirely inside the redemptions table
    // until an admin acts, in which case this edge should be deleted.
    OrderStatus.RedemptionFailed,
  ],

  [OrderStatus.Redeemed]: [
    OrderStatus.Fulfilled, // SCHEMA
  ],

  // Absorbing under the NORMAL pipeline — nothing in the automatic flow
  // moves these forward. Whether they can still move via an admin override
  // is decided independently in ADMIN_OVERRIDE_TRANSITIONS below.
  [OrderStatus.Fulfilled]: [],
  [OrderStatus.PaymentFailed]: [],
  [OrderStatus.FulfillmentFailed]: [],
  [OrderStatus.RedemptionFailed]: [],
  [OrderStatus.Expired]: [],
  [OrderStatus.Cancelled]: [],
  [OrderStatus.Refunded]: [],
};

/**
 * Administrative override transitions — an ops/admin actor stepping outside
 * the normal pipeline. Every one of the 22 OrderStatus members has an
 * explicit entry, most of them empty.
 *
 * `cancelled` is reachable ONLY from the four states the schema's comment
 * literally names: draft/pending_payment (nothing was ever paid — there's
 * nothing to refund, cancellation is the correct terminal action) and
 * vendor_declined/vendor_timeout (schema explicitly writes `→ cancelled` as
 * the alternative to reassignment). It is NOT extended to any other state —
 * "cancelled" stops being a meaningful label once fulfillment work or a
 * reveal has actually happened; refund is the correct tool from there.
 *
 * `refunded` is reachable from every state that can only be reached AFTER
 * `paid` — i.e. every state except {draft, pending_payment, payment_failed},
 * because those three represent "no payment was ever captured." This is a
 * close-to-literal reading of the Brief's "[any] → refunded (admin action)":
 * once money has moved, ops can always reverse it, from wherever the order
 * happens to be stuck.
 *
 * UNRESOLVED — deliberately NOT decided here, not silently picked:
 * vendor_declined and vendor_timeout both legally permit EITHER cancelled OR
 * refunded. By the time either state is reached, payment was already
 * captured (paid → processing happened earlier in the pipeline), so there is
 * a genuine open product question: should a failed vendor reassignment
 * always be refunded (money was taken, nothing was delivered, give it back),
 * always be "cancelled" as a distinct bookkeeping category, or does it
 * legitimately depend on circumstance? This file keeps both edges legal at
 * the guard layer on purpose. The future OrdersService/fulfillment-failure
 * handler must pick one deliberately — this state machine will not make that
 * call implicitly by only including one of the two.
 */
export const ADMIN_OVERRIDE_TRANSITIONS: Readonly<
  Record<OrderStatus, ReadonlyArray<OrderStatus>>
> = {
  [OrderStatus.Draft]: [OrderStatus.Cancelled],
  [OrderStatus.PendingPayment]: [OrderStatus.Cancelled],
  [OrderStatus.Paid]: [OrderStatus.Refunded],
  [OrderStatus.Processing]: [OrderStatus.Refunded],
  [OrderStatus.VendorNotified]: [OrderStatus.Refunded],
  [OrderStatus.VendorAccepted]: [OrderStatus.Refunded],
  // UNRESOLVED — see file-level comment above.
  [OrderStatus.VendorDeclined]: [OrderStatus.Cancelled, OrderStatus.Refunded],
  [OrderStatus.VendorTimeout]: [OrderStatus.Cancelled, OrderStatus.Refunded],
  [OrderStatus.FulfillmentInProgress]: [OrderStatus.Refunded],
  [OrderStatus.Dispatched]: [OrderStatus.Refunded],
  [OrderStatus.Delivered]: [OrderStatus.Refunded],
  [OrderStatus.VoucherIssued]: [OrderStatus.Refunded],
  [OrderStatus.ReadyForRedemption]: [OrderStatus.Refunded],
  [OrderStatus.RevealOpened]: [OrderStatus.Refunded],
  [OrderStatus.Redeemed]: [OrderStatus.Refunded],
  [OrderStatus.Fulfilled]: [OrderStatus.Refunded],
  [OrderStatus.FulfillmentFailed]: [OrderStatus.Refunded],
  [OrderStatus.RedemptionFailed]: [OrderStatus.Refunded],
  [OrderStatus.Expired]: [OrderStatus.Refunded],
  // No payment was ever captured for these — nothing to refund, and
  // cancelling something that already failed/never started isn't meaningful.
  [OrderStatus.PaymentFailed]: [],
  // Fully absorbing: once cancelled or refunded, that's the end of the
  // order's life in this state machine. No re-cancel, no refund-after-cancel
  // (see the UNRESOLVED note — if that gets resolved in favour of "always
  // refund", a cancelled-then-refunded path may need to be added here).
  [OrderStatus.Cancelled]: [],
  [OrderStatus.Refunded]: [],
};

/** True if `to` is reachable from `from` via the normal, automatic pipeline. */
export function isNormalTransition(
  from: OrderStatus,
  to: OrderStatus,
): boolean {
  return NORMAL_TRANSITIONS[from].includes(to);
}

/** True if `to` is reachable from `from` via an explicit admin override. */
export function isAdminOverrideTransition(
  from: OrderStatus,
  to: OrderStatus,
): boolean {
  return ADMIN_OVERRIDE_TRANSITIONS[from].includes(to);
}

/**
 * True if `to` is reachable from `from` at all — normal OR admin override.
 * Read-only introspection (e.g. "what buttons should the ops UI show for
 * this order?"). Enforcement should use the more specific
 * assertNormalTransition / assertAdminOverrideTransition on
 * OrderStateMachineService, not this — see the file-level comment on why
 * normal and admin paths are checked separately at the call site.
 */
export function canTransition(from: OrderStatus, to: OrderStatus): boolean {
  return isNormalTransition(from, to) || isAdminOverrideTransition(from, to);
}

/** All states reachable from `from`, normal and admin-override combined. */
export function getAllowedTransitions(
  from: OrderStatus,
): ReadonlyArray<OrderStatus> {
  return [...NORMAL_TRANSITIONS[from], ...ADMIN_OVERRIDE_TRANSITIONS[from]];
}

/**
 * True only if NEITHER the normal pipeline NOR an admin override can move
 * this order anywhere else. Currently: payment_failed, cancelled, refunded.
 * Note `fulfilled`/`expired`/`fulfillment_failed`/`redemption_failed` are
 * NOT terminal by this definition — they have no normal forward path, but
 * remain refundable by an admin, which is exactly the distinction this
 * function is meant to surface.
 */
export function isTerminal(status: OrderStatus): boolean {
  return (
    NORMAL_TRANSITIONS[status].length === 0 &&
    ADMIN_OVERRIDE_TRANSITIONS[status].length === 0
  );
}
